added otlp exampler support
ansrivas/fiberprometheus pull request #223
Opened 2024-11-26 19:49 UTC by kirankumar-grootan

2025-01-21 15:10 UTC, gaby commented
@kirankumar-grootan Can you add a unit-test for this?

2025-02-10 15:41 UTC, kirankumar-grootan commented
@gaby  I added a test case for this, which requires some setup for the OTLP part. I included a helper function within the same test file. Should I move it to a separate file, or is it better to keep it at the end of the test file?

2025-02-12 11:19 UTC, gaby requested changes
Overall looks good to me, just two simple comments.

2025-02-12 11:19 UTC, gaby commented on go.mod
> +toolchain go1.23.3
Remove this line

2025-02-12 11:19 UTC, gaby commented on go.mod
> +go 1.22.0
Remove the .0

2025-02-12 11:19 UTC, gaby commented on middleware_test.go
> +func otelTracingInit(t *testing.T) {
Probably better to put this at the top of the file before any unit-test

2025-02-12 11:19 UTC, gaby commented
@kirankumar-grootan Added some comments, thanks for the PR 💪

2025-02-12 15:35 UTC, kirankumar-grootan commented on go.mod
> +go 1.22.0
reverted the change

2025-02-12 15:35 UTC, kirankumar-grootan commented on middleware_test.go
> +func otelTracingInit(t *testing.T) {
moved the helpers to top the file

2025-02-12 15:36 UTC, kirankumar-grootan commented
@gaby addressed all the comments in the MR

2025-02-13 09:19 UTC, gaby commented
@kirankumar-grootan You may have to run "go mod tidy"

2025-02-13 11:36 UTC, kirankumar-grootan commented
> @kirankumar-grootan You may have to run "go mod tidy"

applied but `go mod tidy` is changing from `go 1.22` to `go 1.22.0`.  and its due to the otlp sdk 
`go: go.opentelemetry.io/auto/sdk@v1.1.0 requires go@1.22.0, but 1.22 is requested`.

2025-02-13 11:45 UTC, kirankumar-grootan commented on go.mod
> +go 1.22.0
> @kirankumar-grootan You may have to run "go mod tidy"

applied `go mod tidy -go=1.22` but its is changing from `go 1.22` to `go 1.22.0`.  and its due to the otlp sdk 
`go: go.opentelemetry.io/auto/sdk@v1.1.0 requires go@1.22.0, but 1.22 is requested`. 

this is the version im using in my local `go version go1.22.12 darwin/amd64`

2025-02-18 14:12 UTC, gaby approved these changes
LGTM,  I do wonder if making the "EnableOpenMetrics" a param makes sense though

2025-02-18 14:12 UTC, gaby commented
@kirankumar-grootan Thoughts?

2025-02-18 14:21 UTC, gaby commented
@kirankumar-grootan can you run "go mod tidy" once more. Thanks. Will merge after

2025-02-19 04:06 UTC, kirankumar-grootan commented
> LGTM, I do wonder if making the "EnableOpenMetrics" a param makes sense though

Hmm, didn't think of making it optional, as we are using OTLP + metrics for all our services. I will check.

2025-02-19 04:19 UTC, kirankumar-grootan commented
> go mod tidy

no changes to commit after `go mod tidy`

2025-02-19 09:11 UTC, gaby commented
> > LGTM, I do wonder if making the "EnableOpenMetrics" a param makes sense though
> 
> Hmm, I hadn't considered making it optional since we're using OTLP and metrics for all our services.
> 
> The fact is, traces are only scraped with exemplars when the `Accept: application/openmetrics-text` header is included, which happens only if Prometheus is enabled with the exemplar feature. Otherwise, it will scrape standard non-exemplar metrics, so the fallback happens automatically without any extra effort.
> 
> I will check and let you know if there is a better way to turn this on when required.

That's fine then.

2025-02-19 09:12 UTC, gaby commented
> > @kirankumar-grootan can you run "go mod tidy" once more. Thanks. Will merge after
> 
> no changes to commit after `go mod tidy`

Ahhh, you have to rebase your branch. Its complaining about merge conflict with `master`

2025-02-19 15:40 UTC, gaby approved these changes
LGTM

2025-02-24 05:23 UTC, gaby commented
@kirankumar-grootan For some reason GitHub says that commits do not have verified signatures, so it doesn't let me merge it.

2025-02-25 09:08 UTC, kirankumar-grootan commented
> @kirankumar-grootan For some reason GitHub says that commits do not have verified signatures, so it doesn't let me merge it.

IDK what went wrong with my gpg key. now all commits are verified

2025-02-25 11:36 UTC, gaby commented
@kirankumar-grootan That fixed it. Will merge today. Thank you

2025-02-26 11:25 UTC, merged